# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlkit/primordium/locale/primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dlkit.primordium.type import primitives_pb2 as dlkit_dot_primordium_dot_type_dot_primitives__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlkit/primordium/locale/primitives.proto',
  package='dlkit.primordium.locale.primitives',
  syntax='proto3',
  serialized_pb=_b('\n(dlkit/primordium/locale/primitives.proto\x12\"dlkit.primordium.locale.primitives\x1a&dlkit/primordium/type/primitives.proto\"\xdd\x01\n\x0b\x44isplayText\x12\x0c\n\x04text\x18\x01 \x01(\t\x12>\n\x0e\x66ormat_type_id\x18\x02 \x01(\x0b\x32&.dlkit.primordium.type.primitives.Type\x12@\n\x10language_type_id\x18\x03 \x01(\x0b\x32&.dlkit.primordium.type.primitives.Type\x12>\n\x0escript_type_id\x18\x04 \x01(\x0b\x32&.dlkit.primordium.type.primitives.Typeb\x06proto3')
  ,
  dependencies=[dlkit_dot_primordium_dot_type_dot_primitives__pb2.DESCRIPTOR,])




_DISPLAYTEXT = _descriptor.Descriptor(
  name='DisplayText',
  full_name='dlkit.primordium.locale.primitives.DisplayText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='dlkit.primordium.locale.primitives.DisplayText.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format_type_id', full_name='dlkit.primordium.locale.primitives.DisplayText.format_type_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language_type_id', full_name='dlkit.primordium.locale.primitives.DisplayText.language_type_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='script_type_id', full_name='dlkit.primordium.locale.primitives.DisplayText.script_type_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=342,
)

_DISPLAYTEXT.fields_by_name['format_type_id'].message_type = dlkit_dot_primordium_dot_type_dot_primitives__pb2._TYPE
_DISPLAYTEXT.fields_by_name['language_type_id'].message_type = dlkit_dot_primordium_dot_type_dot_primitives__pb2._TYPE
_DISPLAYTEXT.fields_by_name['script_type_id'].message_type = dlkit_dot_primordium_dot_type_dot_primitives__pb2._TYPE
DESCRIPTOR.message_types_by_name['DisplayText'] = _DISPLAYTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DisplayText = _reflection.GeneratedProtocolMessageType('DisplayText', (_message.Message,), dict(
  DESCRIPTOR = _DISPLAYTEXT,
  __module__ = 'dlkit.primordium.locale.primitives_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.primordium.locale.primitives.DisplayText)
  ))
_sym_db.RegisterMessage(DisplayText)


# @@protoc_insertion_point(module_scope)
