OSID_OBJECT_RECORD_TYPES = {
    'enclosure': {
        'authority': 'ODL.MIT.EDU',
        'namespace': 'osid-object',
        'identifier': 'enclosure',
        'display_name': 'Enclosure',
        'display_label': 'Enclosure',
        'description': 'OsidObject record for enclosing a foreign object',
        'domain': 'osid.OsidObject',
        'module_path': 'dlkit.records.osid.object_records',
        'object_record_class_name': 'EnclosureRecord',
        'form_record_class_name': 'EnclosureFormRecord',
        'query_record_class_name': 'EnclosureQueryRecord'},
    'simple-child-sequencing': {
        'authority': 'ODL.MIT.EDU',
        'namespace': 'osid-object',
        'identifier': 'simple-child-sequencing',
        'display_name': 'Simple Child Sequencing',
        'display_label': 'Simple Child Sequencing',
        'description': 'Object record extension for adding child sequencing',
        'domain': 'osid.OsidObject',
        'module_path': 'dlkit.records.osid.object_records',
        'object_record_class_name': 'SimpleChildSequencingRecord',
        'form_record_class_name': 'SimpleChildSequencingFormRecord'},
    'multi-language': {
        'authority': 'ODL.MIT.EDU',
        'namespace': 'osid-object',
        'identifier': 'multi-language',
        'display_name': 'Multi-Language',
        'display_label': 'Multi-Language',
        'description': 'Object record extension for multiple languages in displayName and description',
        'domain': 'osid.OsidObject',
        'module_path': 'dlkit.records.osid.base_records',
        'object_record_class_name': 'MultiLanguageRecord',
        'form_record_class_name': 'MultiLanguageFormRecord',
        'query_record_class_name': 'MultiLanguageQueryRecord'},
    'time-value': {
        'authority': 'ODL.MIT.EDU',
        'namespace': 'osid-object',
        'identifier': 'time-value',
        'display_name': 'Time Value',
        'display_label': 'Time Value',
        'description': 'Object record extension for including a time value',
        'domain': 'osid.OsidObject',
        'module_path': 'dlkit.records.osid.base_records',
        'object_record_class_name': 'TimeValueRecord',
        'form_record_class_name': 'TimeValueFormRecord'}
}
