/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.repeatedFields_, null);
};
goog.inherits(proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.displayName = 'proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.toObject = function(opt_includeInstance) {
  return proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.toObject = function(includeInstance, msg) {
  var f, obj = {
    valuesList: jspb.Message.getRepeatedFloatingPointField(msg, 1),
    uncertaintyMinus: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    uncertaintyPlus: +jspb.Message.getFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate}
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate;
  return proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate}
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Array.<number>} */ (reader.readPackedFloat());
      msg.setValuesList(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setUncertaintyMinus(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setUncertaintyPlus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writePackedFloat(
      1,
      f
    );
  }
  f = message.getUncertaintyMinus();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getUncertaintyPlus();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
};


/**
 * repeated float values = 1;
 * @return {!Array.<number>}
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.getValuesList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/** @param {!Array.<number>} value */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.setValuesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.addValues = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.clearValuesList = function() {
  this.setValuesList([]);
};


/**
 * optional float uncertainty_minus = 2;
 * @return {number}
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.getUncertaintyMinus = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.setUncertaintyMinus = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float uncertainty_plus = 3;
 * @return {number}
 */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.getUncertaintyPlus = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.dlkit.primordium.mapping.coordinate_primitives.Coordinate.prototype.setUncertaintyPlus = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


goog.object.extend(exports, proto.dlkit.primordium.mapping.coordinate_primitives);
