# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primordium/type/primitives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primordium/type/primitives.proto',
  package='dlkit.primordium.type.primitives',
  syntax='proto3',
  serialized_pb=_b('\n primordium/type/primitives.proto\x12 dlkit.primordium.type.primitives\"\x8c\x02\n\x04Type\x12\x11\n\tauthority\x18\x01 \x01(\t\x12\x42\n\x0b\x64\x65scription\x18\x02 \x01(\x0b\x32-.dlkit.primordium.type.primitives.DisplayText\x12\x44\n\rdisplay_label\x18\x03 \x01(\x0b\x32-.dlkit.primordium.type.primitives.DisplayText\x12\x43\n\x0c\x64isplay_name\x18\x04 \x01(\x0b\x32-.dlkit.primordium.type.primitives.DisplayText\x12\x0e\n\x06\x64omain\x18\x05 \x01(\t\x12\x12\n\nidentifier\x18\x06 \x01(\t\"\xdd\x01\n\x0b\x44isplayText\x12\x0c\n\x04text\x18\x01 \x01(\t\x12>\n\x0e\x66ormat_type_id\x18\x02 \x01(\x0b\x32&.dlkit.primordium.type.primitives.Type\x12@\n\x10language_type_id\x18\x03 \x01(\x0b\x32&.dlkit.primordium.type.primitives.Type\x12>\n\x0escript_type_id\x18\x04 \x01(\x0b\x32&.dlkit.primordium.type.primitives.Typeb\x06proto3')
)




_TYPE = _descriptor.Descriptor(
  name='Type',
  full_name='dlkit.primordium.type.primitives.Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authority', full_name='dlkit.primordium.type.primitives.Type.authority', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='dlkit.primordium.type.primitives.Type.description', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_label', full_name='dlkit.primordium.type.primitives.Type.display_label', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='dlkit.primordium.type.primitives.Type.display_name', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='dlkit.primordium.type.primitives.Type.domain', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='dlkit.primordium.type.primitives.Type.identifier', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=339,
)


_DISPLAYTEXT = _descriptor.Descriptor(
  name='DisplayText',
  full_name='dlkit.primordium.type.primitives.DisplayText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='dlkit.primordium.type.primitives.DisplayText.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format_type_id', full_name='dlkit.primordium.type.primitives.DisplayText.format_type_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language_type_id', full_name='dlkit.primordium.type.primitives.DisplayText.language_type_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='script_type_id', full_name='dlkit.primordium.type.primitives.DisplayText.script_type_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=563,
)

_TYPE.fields_by_name['description'].message_type = _DISPLAYTEXT
_TYPE.fields_by_name['display_label'].message_type = _DISPLAYTEXT
_TYPE.fields_by_name['display_name'].message_type = _DISPLAYTEXT
_DISPLAYTEXT.fields_by_name['format_type_id'].message_type = _TYPE
_DISPLAYTEXT.fields_by_name['language_type_id'].message_type = _TYPE
_DISPLAYTEXT.fields_by_name['script_type_id'].message_type = _TYPE
DESCRIPTOR.message_types_by_name['Type'] = _TYPE
DESCRIPTOR.message_types_by_name['DisplayText'] = _DISPLAYTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Type = _reflection.GeneratedProtocolMessageType('Type', (_message.Message,), dict(
  DESCRIPTOR = _TYPE,
  __module__ = 'primordium.type.primitives_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.primordium.type.primitives.Type)
  ))
_sym_db.RegisterMessage(Type)

DisplayText = _reflection.GeneratedProtocolMessageType('DisplayText', (_message.Message,), dict(
  DESCRIPTOR = _DISPLAYTEXT,
  __module__ = 'primordium.type.primitives_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.primordium.type.primitives.DisplayText)
  ))
_sym_db.RegisterMessage(DisplayText)


# @@protoc_insertion_point(module_scope)
