# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dlkit.proto import authentication_pb2 as dlkit_dot_proto_dot_authentication__pb2


class AgentLookupSessionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAgencyId = channel.unary_unary(
        '/dlkit.proto.authentication.AgentLookupSession/GetAgencyId',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgencyIdRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgencyIdReply.FromString,
        )
    self.GetAgency = channel.unary_unary(
        '/dlkit.proto.authentication.AgentLookupSession/GetAgency',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgencyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgencyReply.FromString,
        )
    self.CanLookupAgents = channel.unary_unary(
        '/dlkit.proto.authentication.AgentLookupSession/CanLookupAgents',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.CanLookupAgentsRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.CanLookupAgentsReply.FromString,
        )
    self.UseComparativeAgentView = channel.unary_unary(
        '/dlkit.proto.authentication.AgentLookupSession/UseComparativeAgentView',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.UseComparativeAgentViewRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.UseComparativeAgentViewReply.FromString,
        )
    self.UsePlenaryAgentView = channel.unary_unary(
        '/dlkit.proto.authentication.AgentLookupSession/UsePlenaryAgentView',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.UsePlenaryAgentViewRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.UsePlenaryAgentViewReply.FromString,
        )
    self.UseFederatedAgencyView = channel.unary_unary(
        '/dlkit.proto.authentication.AgentLookupSession/UseFederatedAgencyView',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.UseFederatedAgencyViewRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.UseFederatedAgencyViewReply.FromString,
        )
    self.UseIsolatedAgencyView = channel.unary_unary(
        '/dlkit.proto.authentication.AgentLookupSession/UseIsolatedAgencyView',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.UseIsolatedAgencyViewRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.UseIsolatedAgencyViewReply.FromString,
        )
    self.GetAgent = channel.unary_unary(
        '/dlkit.proto.authentication.AgentLookupSession/GetAgent',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentReply.FromString,
        )
    self.GetAgentsByIds = channel.unary_stream(
        '/dlkit.proto.authentication.AgentLookupSession/GetAgentsByIds',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsByIdsRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.Agent.FromString,
        )
    self.GetAgentsByGenusType = channel.unary_stream(
        '/dlkit.proto.authentication.AgentLookupSession/GetAgentsByGenusType',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsByGenusTypeRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.Agent.FromString,
        )
    self.GetAgentsByParentGenusType = channel.unary_stream(
        '/dlkit.proto.authentication.AgentLookupSession/GetAgentsByParentGenusType',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsByParentGenusTypeRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.Agent.FromString,
        )
    self.GetAgentsByRecordType = channel.unary_stream(
        '/dlkit.proto.authentication.AgentLookupSession/GetAgentsByRecordType',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsByRecordTypeRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.Agent.FromString,
        )
    self.GetAgents = channel.unary_stream(
        '/dlkit.proto.authentication.AgentLookupSession/GetAgents',
        request_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_authentication__pb2.Agent.FromString,
        )


class AgentLookupSessionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAgencyId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgency(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CanLookupAgents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UseComparativeAgentView(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UsePlenaryAgentView(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UseFederatedAgencyView(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UseIsolatedAgencyView(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgentsByIds(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgentsByGenusType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgentsByParentGenusType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgentsByRecordType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentLookupSessionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAgencyId': grpc.unary_unary_rpc_method_handler(
          servicer.GetAgencyId,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgencyIdRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgencyIdReply.SerializeToString,
      ),
      'GetAgency': grpc.unary_unary_rpc_method_handler(
          servicer.GetAgency,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgencyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgencyReply.SerializeToString,
      ),
      'CanLookupAgents': grpc.unary_unary_rpc_method_handler(
          servicer.CanLookupAgents,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.CanLookupAgentsRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.CanLookupAgentsReply.SerializeToString,
      ),
      'UseComparativeAgentView': grpc.unary_unary_rpc_method_handler(
          servicer.UseComparativeAgentView,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.UseComparativeAgentViewRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.UseComparativeAgentViewReply.SerializeToString,
      ),
      'UsePlenaryAgentView': grpc.unary_unary_rpc_method_handler(
          servicer.UsePlenaryAgentView,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.UsePlenaryAgentViewRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.UsePlenaryAgentViewReply.SerializeToString,
      ),
      'UseFederatedAgencyView': grpc.unary_unary_rpc_method_handler(
          servicer.UseFederatedAgencyView,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.UseFederatedAgencyViewRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.UseFederatedAgencyViewReply.SerializeToString,
      ),
      'UseIsolatedAgencyView': grpc.unary_unary_rpc_method_handler(
          servicer.UseIsolatedAgencyView,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.UseIsolatedAgencyViewRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.UseIsolatedAgencyViewReply.SerializeToString,
      ),
      'GetAgent': grpc.unary_unary_rpc_method_handler(
          servicer.GetAgent,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentReply.SerializeToString,
      ),
      'GetAgentsByIds': grpc.unary_stream_rpc_method_handler(
          servicer.GetAgentsByIds,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsByIdsRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.Agent.SerializeToString,
      ),
      'GetAgentsByGenusType': grpc.unary_stream_rpc_method_handler(
          servicer.GetAgentsByGenusType,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsByGenusTypeRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.Agent.SerializeToString,
      ),
      'GetAgentsByParentGenusType': grpc.unary_stream_rpc_method_handler(
          servicer.GetAgentsByParentGenusType,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsByParentGenusTypeRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.Agent.SerializeToString,
      ),
      'GetAgentsByRecordType': grpc.unary_stream_rpc_method_handler(
          servicer.GetAgentsByRecordType,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsByRecordTypeRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.Agent.SerializeToString,
      ),
      'GetAgents': grpc.unary_stream_rpc_method_handler(
          servicer.GetAgents,
          request_deserializer=dlkit_dot_proto_dot_authentication__pb2.GetAgentsRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_authentication__pb2.Agent.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dlkit.proto.authentication.AgentLookupSession', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
