# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dlkit.primordium.id import primitives_pb2 as dlkit_dot_primordium_dot_id_dot_primitives__pb2
from dlkit.proto import hierarchy_pb2 as dlkit_dot_proto_dot_hierarchy__pb2


class HierarchyTraversalSessionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetHierarchyId = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/GetHierarchyId',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyIdRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyIdReply.FromString,
        )
    self.GetHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/GetHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyReply.FromString,
        )
    self.CanAccessHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/CanAccessHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanAccessHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanAccessHierarchyReply.FromString,
        )
    self.GetRoots = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/GetRoots',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetRootsRequest.SerializeToString,
        response_deserializer=dlkit_dot_primordium_dot_id_dot_primitives__pb2.Id.FromString,
        )
    self.HasParents = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/HasParents',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.HasParentsRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.HasParentsReply.FromString,
        )
    self.IsParent = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/IsParent',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.IsParentRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.IsParentReply.FromString,
        )
    self.GetParents = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/GetParents',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetParentsRequest.SerializeToString,
        response_deserializer=dlkit_dot_primordium_dot_id_dot_primitives__pb2.Id.FromString,
        )
    self.IsAncestor = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/IsAncestor',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.IsAncestorRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.IsAncestorReply.FromString,
        )
    self.HasChildren = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/HasChildren',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.HasChildrenRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.HasChildrenReply.FromString,
        )
    self.IsChild = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/IsChild',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.IsChildRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.IsChildReply.FromString,
        )
    self.GetChildren = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/GetChildren',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetChildrenRequest.SerializeToString,
        response_deserializer=dlkit_dot_primordium_dot_id_dot_primitives__pb2.Id.FromString,
        )
    self.IsDescendant = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/IsDescendant',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.IsDescendantRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.IsDescendantReply.FromString,
        )
    self.GetNodes = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyTraversalSession/GetNodes',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetNodesRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetNodesReply.FromString,
        )


class HierarchyTraversalSessionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetHierarchyId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CanAccessHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRoots(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HasParents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsParent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetParents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsAncestor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HasChildren(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsChild(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChildren(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsDescendant(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HierarchyTraversalSessionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetHierarchyId': grpc.unary_unary_rpc_method_handler(
          servicer.GetHierarchyId,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyIdRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyIdReply.SerializeToString,
      ),
      'GetHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.GetHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyReply.SerializeToString,
      ),
      'CanAccessHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.CanAccessHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanAccessHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanAccessHierarchyReply.SerializeToString,
      ),
      'GetRoots': grpc.unary_stream_rpc_method_handler(
          servicer.GetRoots,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetRootsRequest.FromString,
          response_serializer=dlkit_dot_primordium_dot_id_dot_primitives__pb2.Id.SerializeToString,
      ),
      'HasParents': grpc.unary_unary_rpc_method_handler(
          servicer.HasParents,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.HasParentsRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.HasParentsReply.SerializeToString,
      ),
      'IsParent': grpc.unary_unary_rpc_method_handler(
          servicer.IsParent,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.IsParentRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.IsParentReply.SerializeToString,
      ),
      'GetParents': grpc.unary_stream_rpc_method_handler(
          servicer.GetParents,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetParentsRequest.FromString,
          response_serializer=dlkit_dot_primordium_dot_id_dot_primitives__pb2.Id.SerializeToString,
      ),
      'IsAncestor': grpc.unary_unary_rpc_method_handler(
          servicer.IsAncestor,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.IsAncestorRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.IsAncestorReply.SerializeToString,
      ),
      'HasChildren': grpc.unary_unary_rpc_method_handler(
          servicer.HasChildren,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.HasChildrenRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.HasChildrenReply.SerializeToString,
      ),
      'IsChild': grpc.unary_unary_rpc_method_handler(
          servicer.IsChild,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.IsChildRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.IsChildReply.SerializeToString,
      ),
      'GetChildren': grpc.unary_stream_rpc_method_handler(
          servicer.GetChildren,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetChildrenRequest.FromString,
          response_serializer=dlkit_dot_primordium_dot_id_dot_primitives__pb2.Id.SerializeToString,
      ),
      'IsDescendant': grpc.unary_unary_rpc_method_handler(
          servicer.IsDescendant,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.IsDescendantRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.IsDescendantReply.SerializeToString,
      ),
      'GetNodes': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodes,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetNodesRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetNodesReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dlkit.proto.hierarchy.HierarchyTraversalSession', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class HierarchyDesignSessionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetHierarchyId = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyDesignSession/GetHierarchyId',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyIdRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyIdReply.FromString,
        )
    self.GetHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyDesignSession/GetHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyReply.FromString,
        )
    self.CanModifyHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyDesignSession/CanModifyHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanModifyHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanModifyHierarchyReply.FromString,
        )
    self.AddRoot = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyDesignSession/AddRoot',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.AddRootRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.AddRootReply.FromString,
        )
    self.AddChild = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyDesignSession/AddChild',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.AddChildRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.AddChildReply.FromString,
        )
    self.RemoveRoot = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyDesignSession/RemoveRoot',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveRootRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveRootReply.FromString,
        )
    self.RemoveChild = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyDesignSession/RemoveChild',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveChildRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveChildReply.FromString,
        )
    self.RemoveChildren = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyDesignSession/RemoveChildren',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveChildrenRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveChildrenReply.FromString,
        )


class HierarchyDesignSessionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetHierarchyId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CanModifyHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddRoot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddChild(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveRoot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveChild(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveChildren(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HierarchyDesignSessionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetHierarchyId': grpc.unary_unary_rpc_method_handler(
          servicer.GetHierarchyId,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyIdRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyIdReply.SerializeToString,
      ),
      'GetHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.GetHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyReply.SerializeToString,
      ),
      'CanModifyHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.CanModifyHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanModifyHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanModifyHierarchyReply.SerializeToString,
      ),
      'AddRoot': grpc.unary_unary_rpc_method_handler(
          servicer.AddRoot,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.AddRootRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.AddRootReply.SerializeToString,
      ),
      'AddChild': grpc.unary_unary_rpc_method_handler(
          servicer.AddChild,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.AddChildRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.AddChildReply.SerializeToString,
      ),
      'RemoveRoot': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveRoot,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveRootRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveRootReply.SerializeToString,
      ),
      'RemoveChild': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveChild,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveChildRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveChildReply.SerializeToString,
      ),
      'RemoveChildren': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveChildren,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveChildrenRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.RemoveChildrenReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dlkit.proto.hierarchy.HierarchyDesignSession', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class HierarchyLookupSessionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CanLookupHierarchies = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/CanLookupHierarchies',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanLookupHierarchiesRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanLookupHierarchiesReply.FromString,
        )
    self.UseComparativeHierarchyView = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/UseComparativeHierarchyView',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.UseComparativeHierarchyViewRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.UseComparativeHierarchyViewReply.FromString,
        )
    self.UsePlenaryHierarchyView = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/UsePlenaryHierarchyView',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.UsePlenaryHierarchyViewRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.UsePlenaryHierarchyViewReply.FromString,
        )
    self.GetHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/GetHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyReply.FromString,
        )
    self.GetHierarchiesByIds = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/GetHierarchiesByIds',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByIdsRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.FromString,
        )
    self.GetHierarchiesByGenusType = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/GetHierarchiesByGenusType',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByGenusTypeRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.FromString,
        )
    self.GetHierarchiesByParentGenusType = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/GetHierarchiesByParentGenusType',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByParentGenusTypeRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.FromString,
        )
    self.GetHierarchiesByRecordType = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/GetHierarchiesByRecordType',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByRecordTypeRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.FromString,
        )
    self.GetHierarchiesByProvider = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/GetHierarchiesByProvider',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByProviderRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.FromString,
        )
    self.GetHierarchies = channel.unary_stream(
        '/dlkit.proto.hierarchy.HierarchyLookupSession/GetHierarchies',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.FromString,
        )


class HierarchyLookupSessionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CanLookupHierarchies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UseComparativeHierarchyView(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UsePlenaryHierarchyView(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchiesByIds(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchiesByGenusType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchiesByParentGenusType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchiesByRecordType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchiesByProvider(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HierarchyLookupSessionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CanLookupHierarchies': grpc.unary_unary_rpc_method_handler(
          servicer.CanLookupHierarchies,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanLookupHierarchiesRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanLookupHierarchiesReply.SerializeToString,
      ),
      'UseComparativeHierarchyView': grpc.unary_unary_rpc_method_handler(
          servicer.UseComparativeHierarchyView,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.UseComparativeHierarchyViewRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.UseComparativeHierarchyViewReply.SerializeToString,
      ),
      'UsePlenaryHierarchyView': grpc.unary_unary_rpc_method_handler(
          servicer.UsePlenaryHierarchyView,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.UsePlenaryHierarchyViewRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.UsePlenaryHierarchyViewReply.SerializeToString,
      ),
      'GetHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.GetHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyReply.SerializeToString,
      ),
      'GetHierarchiesByIds': grpc.unary_stream_rpc_method_handler(
          servicer.GetHierarchiesByIds,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByIdsRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.SerializeToString,
      ),
      'GetHierarchiesByGenusType': grpc.unary_stream_rpc_method_handler(
          servicer.GetHierarchiesByGenusType,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByGenusTypeRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.SerializeToString,
      ),
      'GetHierarchiesByParentGenusType': grpc.unary_stream_rpc_method_handler(
          servicer.GetHierarchiesByParentGenusType,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByParentGenusTypeRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.SerializeToString,
      ),
      'GetHierarchiesByRecordType': grpc.unary_stream_rpc_method_handler(
          servicer.GetHierarchiesByRecordType,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByRecordTypeRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.SerializeToString,
      ),
      'GetHierarchiesByProvider': grpc.unary_stream_rpc_method_handler(
          servicer.GetHierarchiesByProvider,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesByProviderRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.SerializeToString,
      ),
      'GetHierarchies': grpc.unary_stream_rpc_method_handler(
          servicer.GetHierarchies,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchiesRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.Hierarchy.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dlkit.proto.hierarchy.HierarchyLookupSession', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class HierarchyAdminSessionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CanCreateHierarchies = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/CanCreateHierarchies',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanCreateHierarchiesRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanCreateHierarchiesReply.FromString,
        )
    self.CanCreateHierarchyWithRecordTypes = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/CanCreateHierarchyWithRecordTypes',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanCreateHierarchyWithRecordTypesRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanCreateHierarchyWithRecordTypesReply.FromString,
        )
    self.GetHierarchyFormForCreate = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/GetHierarchyFormForCreate',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyFormForCreateRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyFormForCreateReply.FromString,
        )
    self.CreateHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/CreateHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CreateHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CreateHierarchyReply.FromString,
        )
    self.CanUpdateHierarchies = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/CanUpdateHierarchies',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanUpdateHierarchiesRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanUpdateHierarchiesReply.FromString,
        )
    self.GetHierarchyFormForUpdate = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/GetHierarchyFormForUpdate',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyFormForUpdateRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyFormForUpdateReply.FromString,
        )
    self.UpdateHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/UpdateHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.UpdateHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.UpdateHierarchyReply.FromString,
        )
    self.CanDeleteHierarchies = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/CanDeleteHierarchies',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanDeleteHierarchiesRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanDeleteHierarchiesReply.FromString,
        )
    self.DeleteHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/DeleteHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.DeleteHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.DeleteHierarchyReply.FromString,
        )
    self.CanManageHierarchyAliases = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/CanManageHierarchyAliases',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanManageHierarchyAliasesRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanManageHierarchyAliasesReply.FromString,
        )
    self.AliasHierarchy = channel.unary_unary(
        '/dlkit.proto.hierarchy.HierarchyAdminSession/AliasHierarchy',
        request_serializer=dlkit_dot_proto_dot_hierarchy__pb2.AliasHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.AliasHierarchyReply.FromString,
        )


class HierarchyAdminSessionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CanCreateHierarchies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CanCreateHierarchyWithRecordTypes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchyFormForCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CanUpdateHierarchies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHierarchyFormForUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CanDeleteHierarchies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CanManageHierarchyAliases(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AliasHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HierarchyAdminSessionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CanCreateHierarchies': grpc.unary_unary_rpc_method_handler(
          servicer.CanCreateHierarchies,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanCreateHierarchiesRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanCreateHierarchiesReply.SerializeToString,
      ),
      'CanCreateHierarchyWithRecordTypes': grpc.unary_unary_rpc_method_handler(
          servicer.CanCreateHierarchyWithRecordTypes,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanCreateHierarchyWithRecordTypesRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanCreateHierarchyWithRecordTypesReply.SerializeToString,
      ),
      'GetHierarchyFormForCreate': grpc.unary_unary_rpc_method_handler(
          servicer.GetHierarchyFormForCreate,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyFormForCreateRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyFormForCreateReply.SerializeToString,
      ),
      'CreateHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.CreateHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CreateHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CreateHierarchyReply.SerializeToString,
      ),
      'CanUpdateHierarchies': grpc.unary_unary_rpc_method_handler(
          servicer.CanUpdateHierarchies,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanUpdateHierarchiesRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanUpdateHierarchiesReply.SerializeToString,
      ),
      'GetHierarchyFormForUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.GetHierarchyFormForUpdate,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyFormForUpdateRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.GetHierarchyFormForUpdateReply.SerializeToString,
      ),
      'UpdateHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.UpdateHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.UpdateHierarchyReply.SerializeToString,
      ),
      'CanDeleteHierarchies': grpc.unary_unary_rpc_method_handler(
          servicer.CanDeleteHierarchies,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanDeleteHierarchiesRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanDeleteHierarchiesReply.SerializeToString,
      ),
      'DeleteHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.DeleteHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.DeleteHierarchyReply.SerializeToString,
      ),
      'CanManageHierarchyAliases': grpc.unary_unary_rpc_method_handler(
          servicer.CanManageHierarchyAliases,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.CanManageHierarchyAliasesRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.CanManageHierarchyAliasesReply.SerializeToString,
      ),
      'AliasHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.AliasHierarchy,
          request_deserializer=dlkit_dot_proto_dot_hierarchy__pb2.AliasHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_hierarchy__pb2.AliasHierarchyReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dlkit.proto.hierarchy.HierarchyAdminSession', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
