# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlkit/proto/id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dlkit.primordium.id import primitives_pb2 as dlkit_dot_primordium_dot_id_dot_primitives__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlkit/proto/id.proto',
  package='dlkit.proto.id',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x64lkit/proto/id.proto\x12\x0e\x64lkit.proto.id\x1a$dlkit/primordium/id/primitives.proto\"\x08\n\x06IdForm\"9\n\x06IdList\x12/\n\x03ids\x18\x01 \x03(\x0b\x32\".dlkit.primordium.id.primitives.Idb\x06proto3')
  ,
  dependencies=[dlkit_dot_primordium_dot_id_dot_primitives__pb2.DESCRIPTOR,])




_IDFORM = _descriptor.Descriptor(
  name='IdForm',
  full_name='dlkit.proto.id.IdForm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=86,
)


_IDLIST = _descriptor.Descriptor(
  name='IdList',
  full_name='dlkit.proto.id.IdList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='dlkit.proto.id.IdList.ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=145,
)

_IDLIST.fields_by_name['ids'].message_type = dlkit_dot_primordium_dot_id_dot_primitives__pb2._ID
DESCRIPTOR.message_types_by_name['IdForm'] = _IDFORM
DESCRIPTOR.message_types_by_name['IdList'] = _IDLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdForm = _reflection.GeneratedProtocolMessageType('IdForm', (_message.Message,), dict(
  DESCRIPTOR = _IDFORM,
  __module__ = 'dlkit.proto.id_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.id.IdForm)
  ))
_sym_db.RegisterMessage(IdForm)

IdList = _reflection.GeneratedProtocolMessageType('IdList', (_message.Message,), dict(
  DESCRIPTOR = _IDLIST,
  __module__ = 'dlkit.proto.id_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.id.IdList)
  ))
_sym_db.RegisterMessage(IdList)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
