# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dlkit.proto import ontology_pb2 as dlkit_dot_proto_dot_ontology__pb2


class SubjectHierarchyDesignSessionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSubjectHierarchyId = channel.unary_unary(
        '/dlkit.proto.ontology.SubjectHierarchyDesignSession/GetSubjectHierarchyId',
        request_serializer=dlkit_dot_proto_dot_ontology__pb2.GetSubjectHierarchyIdRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_ontology__pb2.GetSubjectHierarchyIdReply.FromString,
        )
    self.GetSubjectHierarchy = channel.unary_unary(
        '/dlkit.proto.ontology.SubjectHierarchyDesignSession/GetSubjectHierarchy',
        request_serializer=dlkit_dot_proto_dot_ontology__pb2.GetSubjectHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_ontology__pb2.GetSubjectHierarchyReply.FromString,
        )
    self.CanModifySubjectHierarchy = channel.unary_unary(
        '/dlkit.proto.ontology.SubjectHierarchyDesignSession/CanModifySubjectHierarchy',
        request_serializer=dlkit_dot_proto_dot_ontology__pb2.CanModifySubjectHierarchyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_ontology__pb2.CanModifySubjectHierarchyReply.FromString,
        )
    self.AddRootSubject = channel.unary_unary(
        '/dlkit.proto.ontology.SubjectHierarchyDesignSession/AddRootSubject',
        request_serializer=dlkit_dot_proto_dot_ontology__pb2.AddRootSubjectRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_ontology__pb2.AddRootSubjectReply.FromString,
        )
    self.RemoveRootSubject = channel.unary_unary(
        '/dlkit.proto.ontology.SubjectHierarchyDesignSession/RemoveRootSubject',
        request_serializer=dlkit_dot_proto_dot_ontology__pb2.RemoveRootSubjectRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_ontology__pb2.RemoveRootSubjectReply.FromString,
        )
    self.AddChildSubject = channel.unary_unary(
        '/dlkit.proto.ontology.SubjectHierarchyDesignSession/AddChildSubject',
        request_serializer=dlkit_dot_proto_dot_ontology__pb2.AddChildSubjectRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_ontology__pb2.AddChildSubjectReply.FromString,
        )
    self.RemoveChildSubject = channel.unary_unary(
        '/dlkit.proto.ontology.SubjectHierarchyDesignSession/RemoveChildSubject',
        request_serializer=dlkit_dot_proto_dot_ontology__pb2.RemoveChildSubjectRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_ontology__pb2.RemoveChildSubjectReply.FromString,
        )
    self.RemoveChildSubjects = channel.unary_unary(
        '/dlkit.proto.ontology.SubjectHierarchyDesignSession/RemoveChildSubjects',
        request_serializer=dlkit_dot_proto_dot_ontology__pb2.RemoveChildSubjectsRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_ontology__pb2.RemoveChildSubjectsReply.FromString,
        )


class SubjectHierarchyDesignSessionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSubjectHierarchyId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSubjectHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CanModifySubjectHierarchy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddRootSubject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveRootSubject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddChildSubject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveChildSubject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveChildSubjects(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SubjectHierarchyDesignSessionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSubjectHierarchyId': grpc.unary_unary_rpc_method_handler(
          servicer.GetSubjectHierarchyId,
          request_deserializer=dlkit_dot_proto_dot_ontology__pb2.GetSubjectHierarchyIdRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_ontology__pb2.GetSubjectHierarchyIdReply.SerializeToString,
      ),
      'GetSubjectHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.GetSubjectHierarchy,
          request_deserializer=dlkit_dot_proto_dot_ontology__pb2.GetSubjectHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_ontology__pb2.GetSubjectHierarchyReply.SerializeToString,
      ),
      'CanModifySubjectHierarchy': grpc.unary_unary_rpc_method_handler(
          servicer.CanModifySubjectHierarchy,
          request_deserializer=dlkit_dot_proto_dot_ontology__pb2.CanModifySubjectHierarchyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_ontology__pb2.CanModifySubjectHierarchyReply.SerializeToString,
      ),
      'AddRootSubject': grpc.unary_unary_rpc_method_handler(
          servicer.AddRootSubject,
          request_deserializer=dlkit_dot_proto_dot_ontology__pb2.AddRootSubjectRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_ontology__pb2.AddRootSubjectReply.SerializeToString,
      ),
      'RemoveRootSubject': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveRootSubject,
          request_deserializer=dlkit_dot_proto_dot_ontology__pb2.RemoveRootSubjectRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_ontology__pb2.RemoveRootSubjectReply.SerializeToString,
      ),
      'AddChildSubject': grpc.unary_unary_rpc_method_handler(
          servicer.AddChildSubject,
          request_deserializer=dlkit_dot_proto_dot_ontology__pb2.AddChildSubjectRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_ontology__pb2.AddChildSubjectReply.SerializeToString,
      ),
      'RemoveChildSubject': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveChildSubject,
          request_deserializer=dlkit_dot_proto_dot_ontology__pb2.RemoveChildSubjectRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_ontology__pb2.RemoveChildSubjectReply.SerializeToString,
      ),
      'RemoveChildSubjects': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveChildSubjects,
          request_deserializer=dlkit_dot_proto_dot_ontology__pb2.RemoveChildSubjectsRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_ontology__pb2.RemoveChildSubjectsReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dlkit.proto.ontology.SubjectHierarchyDesignSession', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
