# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlkit/proto/proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlkit/proto/proxy.proto',
  package='dlkit.proto.proxy',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x64lkit/proto/proxy.proto\x12\x11\x64lkit.proto.proxy\"\x07\n\x05Proxy\"\x10\n\x0eProxyCondition\"T\n\x16GetProxyConditionReply\x12:\n\x0fproxy_condition\x18\x01 \x01(\x0b\x32!.dlkit.proto.proxy.ProxyCondition\"\x1a\n\x18GetProxyConditionRequest\"8\n\rGetProxyReply\x12\'\n\x05proxy\x18\x01 \x01(\x0b\x32\x18.dlkit.proto.proxy.Proxy\"D\n\x0fGetProxyRequest\x12\x31\n\x06input_\x18\x01 \x01(\x0b\x32!.dlkit.proto.proxy.ProxyCondition2\xd1\x01\n\x0cProxySession\x12m\n\x11GetProxyCondition\x12+.dlkit.proto.proxy.GetProxyConditionRequest\x1a).dlkit.proto.proxy.GetProxyConditionReply\"\x00\x12R\n\x08GetProxy\x12\".dlkit.proto.proxy.GetProxyRequest\x1a .dlkit.proto.proxy.GetProxyReply\"\x00\x62\x06proto3')
)




_PROXY = _descriptor.Descriptor(
  name='Proxy',
  full_name='dlkit.proto.proxy.Proxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=53,
)


_PROXYCONDITION = _descriptor.Descriptor(
  name='ProxyCondition',
  full_name='dlkit.proto.proxy.ProxyCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=71,
)


_GETPROXYCONDITIONREPLY = _descriptor.Descriptor(
  name='GetProxyConditionReply',
  full_name='dlkit.proto.proxy.GetProxyConditionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proxy_condition', full_name='dlkit.proto.proxy.GetProxyConditionReply.proxy_condition', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=157,
)


_GETPROXYCONDITIONREQUEST = _descriptor.Descriptor(
  name='GetProxyConditionRequest',
  full_name='dlkit.proto.proxy.GetProxyConditionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=185,
)


_GETPROXYREPLY = _descriptor.Descriptor(
  name='GetProxyReply',
  full_name='dlkit.proto.proxy.GetProxyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proxy', full_name='dlkit.proto.proxy.GetProxyReply.proxy', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=243,
)


_GETPROXYREQUEST = _descriptor.Descriptor(
  name='GetProxyRequest',
  full_name='dlkit.proto.proxy.GetProxyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_', full_name='dlkit.proto.proxy.GetProxyRequest.input_', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=313,
)

_GETPROXYCONDITIONREPLY.fields_by_name['proxy_condition'].message_type = _PROXYCONDITION
_GETPROXYREPLY.fields_by_name['proxy'].message_type = _PROXY
_GETPROXYREQUEST.fields_by_name['input_'].message_type = _PROXYCONDITION
DESCRIPTOR.message_types_by_name['Proxy'] = _PROXY
DESCRIPTOR.message_types_by_name['ProxyCondition'] = _PROXYCONDITION
DESCRIPTOR.message_types_by_name['GetProxyConditionReply'] = _GETPROXYCONDITIONREPLY
DESCRIPTOR.message_types_by_name['GetProxyConditionRequest'] = _GETPROXYCONDITIONREQUEST
DESCRIPTOR.message_types_by_name['GetProxyReply'] = _GETPROXYREPLY
DESCRIPTOR.message_types_by_name['GetProxyRequest'] = _GETPROXYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proxy = _reflection.GeneratedProtocolMessageType('Proxy', (_message.Message,), dict(
  DESCRIPTOR = _PROXY,
  __module__ = 'dlkit.proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.proxy.Proxy)
  ))
_sym_db.RegisterMessage(Proxy)

ProxyCondition = _reflection.GeneratedProtocolMessageType('ProxyCondition', (_message.Message,), dict(
  DESCRIPTOR = _PROXYCONDITION,
  __module__ = 'dlkit.proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.proxy.ProxyCondition)
  ))
_sym_db.RegisterMessage(ProxyCondition)

GetProxyConditionReply = _reflection.GeneratedProtocolMessageType('GetProxyConditionReply', (_message.Message,), dict(
  DESCRIPTOR = _GETPROXYCONDITIONREPLY,
  __module__ = 'dlkit.proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.proxy.GetProxyConditionReply)
  ))
_sym_db.RegisterMessage(GetProxyConditionReply)

GetProxyConditionRequest = _reflection.GeneratedProtocolMessageType('GetProxyConditionRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPROXYCONDITIONREQUEST,
  __module__ = 'dlkit.proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.proxy.GetProxyConditionRequest)
  ))
_sym_db.RegisterMessage(GetProxyConditionRequest)

GetProxyReply = _reflection.GeneratedProtocolMessageType('GetProxyReply', (_message.Message,), dict(
  DESCRIPTOR = _GETPROXYREPLY,
  __module__ = 'dlkit.proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.proxy.GetProxyReply)
  ))
_sym_db.RegisterMessage(GetProxyReply)

GetProxyRequest = _reflection.GeneratedProtocolMessageType('GetProxyRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPROXYREQUEST,
  __module__ = 'dlkit.proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.proxy.GetProxyRequest)
  ))
_sym_db.RegisterMessage(GetProxyRequest)



_PROXYSESSION = _descriptor.ServiceDescriptor(
  name='ProxySession',
  full_name='dlkit.proto.proxy.ProxySession',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=316,
  serialized_end=525,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProxyCondition',
    full_name='dlkit.proto.proxy.ProxySession.GetProxyCondition',
    index=0,
    containing_service=None,
    input_type=_GETPROXYCONDITIONREQUEST,
    output_type=_GETPROXYCONDITIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetProxy',
    full_name='dlkit.proto.proxy.ProxySession.GetProxy',
    index=1,
    containing_service=None,
    input_type=_GETPROXYREQUEST,
    output_type=_GETPROXYREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROXYSESSION)

DESCRIPTOR.services_by_name['ProxySession'] = _PROXYSESSION

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ProxySessionStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetProxyCondition = channel.unary_unary(
          '/dlkit.proto.proxy.ProxySession/GetProxyCondition',
          request_serializer=GetProxyConditionRequest.SerializeToString,
          response_deserializer=GetProxyConditionReply.FromString,
          )
      self.GetProxy = channel.unary_unary(
          '/dlkit.proto.proxy.ProxySession/GetProxy',
          request_serializer=GetProxyRequest.SerializeToString,
          response_deserializer=GetProxyReply.FromString,
          )


  class ProxySessionServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetProxyCondition(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetProxy(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ProxySessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetProxyCondition': grpc.unary_unary_rpc_method_handler(
            servicer.GetProxyCondition,
            request_deserializer=GetProxyConditionRequest.FromString,
            response_serializer=GetProxyConditionReply.SerializeToString,
        ),
        'GetProxy': grpc.unary_unary_rpc_method_handler(
            servicer.GetProxy,
            request_deserializer=GetProxyRequest.FromString,
            response_serializer=GetProxyReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'dlkit.proto.proxy.ProxySession', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaProxySessionServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetProxyCondition(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetProxy(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaProxySessionStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetProxyCondition(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetProxyCondition.future = None
    def GetProxy(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetProxy.future = None


  def beta_create_ProxySession_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('dlkit.proto.proxy.ProxySession', 'GetProxy'): GetProxyRequest.FromString,
      ('dlkit.proto.proxy.ProxySession', 'GetProxyCondition'): GetProxyConditionRequest.FromString,
    }
    response_serializers = {
      ('dlkit.proto.proxy.ProxySession', 'GetProxy'): GetProxyReply.SerializeToString,
      ('dlkit.proto.proxy.ProxySession', 'GetProxyCondition'): GetProxyConditionReply.SerializeToString,
    }
    method_implementations = {
      ('dlkit.proto.proxy.ProxySession', 'GetProxy'): face_utilities.unary_unary_inline(servicer.GetProxy),
      ('dlkit.proto.proxy.ProxySession', 'GetProxyCondition'): face_utilities.unary_unary_inline(servicer.GetProxyCondition),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ProxySession_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('dlkit.proto.proxy.ProxySession', 'GetProxy'): GetProxyRequest.SerializeToString,
      ('dlkit.proto.proxy.ProxySession', 'GetProxyCondition'): GetProxyConditionRequest.SerializeToString,
    }
    response_deserializers = {
      ('dlkit.proto.proxy.ProxySession', 'GetProxy'): GetProxyReply.FromString,
      ('dlkit.proto.proxy.ProxySession', 'GetProxyCondition'): GetProxyConditionReply.FromString,
    }
    cardinalities = {
      'GetProxy': cardinality.Cardinality.UNARY_UNARY,
      'GetProxyCondition': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'dlkit.proto.proxy.ProxySession', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
