# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dlkit.proto import proxy_pb2 as dlkit_dot_proto_dot_proxy__pb2


class ProxySessionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProxyCondition = channel.unary_unary(
        '/dlkit.proto.proxy.ProxySession/GetProxyCondition',
        request_serializer=dlkit_dot_proto_dot_proxy__pb2.GetProxyConditionRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_proxy__pb2.GetProxyConditionReply.FromString,
        )
    self.GetProxy = channel.unary_unary(
        '/dlkit.proto.proxy.ProxySession/GetProxy',
        request_serializer=dlkit_dot_proto_dot_proxy__pb2.GetProxyRequest.SerializeToString,
        response_deserializer=dlkit_dot_proto_dot_proxy__pb2.GetProxyReply.FromString,
        )


class ProxySessionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProxyCondition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProxy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProxySessionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProxyCondition': grpc.unary_unary_rpc_method_handler(
          servicer.GetProxyCondition,
          request_deserializer=dlkit_dot_proto_dot_proxy__pb2.GetProxyConditionRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_proxy__pb2.GetProxyConditionReply.SerializeToString,
      ),
      'GetProxy': grpc.unary_unary_rpc_method_handler(
          servicer.GetProxy,
          request_deserializer=dlkit_dot_proto_dot_proxy__pb2.GetProxyRequest.FromString,
          response_serializer=dlkit_dot_proto_dot_proxy__pb2.GetProxyReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dlkit.proto.proxy.ProxySession', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
