# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlkit/proto/transport.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dlkit.primordium.id import primitives_pb2 as dlkit_dot_primordium_dot_id_dot_primitives__pb2
from dlkit.primordium.locale import primitives_pb2 as dlkit_dot_primordium_dot_locale_dot_primitives__pb2
from dlkit.primordium.type import primitives_pb2 as dlkit_dot_primordium_dot_type_dot_primitives__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlkit/proto/transport.proto',
  package='dlkit.proto.transport',
  syntax='proto3',
  serialized_pb=_b('\n\x1b\x64lkit/proto/transport.proto\x12\x15\x64lkit.proto.transport\x1a$dlkit/primordium/id/primitives.proto\x1a(dlkit/primordium/locale/primitives.proto\x1a&dlkit/primordium/type/primitives.proto\"\xc2\x02\n\x08\x45ndpoint\x12\x44\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32/.dlkit.primordium.locale.primitives.DisplayText\x12\x44\n\x0b\x64isplayName\x18\x02 \x01(\x0b\x32/.dlkit.primordium.locale.primitives.DisplayText\x12;\n\x0bgenusTypeId\x18\x03 \x01(\x0b\x32&.dlkit.primordium.type.primitives.Type\x12.\n\x02id\x18\x04 \x01(\x0b\x32\".dlkit.primordium.id.primitives.Id\x12=\n\rrecordTypeIds\x18\x05 \x03(\x0b\x32&.dlkit.primordium.type.primitives.Type\"B\n\x0c\x45ndpointList\x12\x32\n\tendpoints\x18\x01 \x03(\x0b\x32\x1f.dlkit.proto.transport.Endpoint\"\t\n\x07Request\"\xc2\x02\n\x08Response\x12\x44\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32/.dlkit.primordium.locale.primitives.DisplayText\x12\x44\n\x0b\x64isplayName\x18\x02 \x01(\x0b\x32/.dlkit.primordium.locale.primitives.DisplayText\x12;\n\x0bgenusTypeId\x18\x03 \x01(\x0b\x32&.dlkit.primordium.type.primitives.Type\x12.\n\x02id\x18\x04 \x01(\x0b\x32\".dlkit.primordium.id.primitives.Id\x12=\n\rrecordTypeIds\x18\x05 \x03(\x0b\x32&.dlkit.primordium.type.primitives.Type\"\x11\n\x0f\x44\x61taInputStream\"\x12\n\x10\x44\x61taOutputStreamb\x06proto3')
  ,
  dependencies=[dlkit_dot_primordium_dot_id_dot_primitives__pb2.DESCRIPTOR,dlkit_dot_primordium_dot_locale_dot_primitives__pb2.DESCRIPTOR,dlkit_dot_primordium_dot_type_dot_primitives__pb2.DESCRIPTOR,])




_ENDPOINT = _descriptor.Descriptor(
  name='Endpoint',
  full_name='dlkit.proto.transport.Endpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='dlkit.proto.transport.Endpoint.description', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='dlkit.proto.transport.Endpoint.displayName', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genusTypeId', full_name='dlkit.proto.transport.Endpoint.genusTypeId', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='dlkit.proto.transport.Endpoint.id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recordTypeIds', full_name='dlkit.proto.transport.Endpoint.recordTypeIds', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=497,
)


_ENDPOINTLIST = _descriptor.Descriptor(
  name='EndpointList',
  full_name='dlkit.proto.transport.EndpointList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoints', full_name='dlkit.proto.transport.EndpointList.endpoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=565,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='dlkit.proto.transport.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=576,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='dlkit.proto.transport.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='dlkit.proto.transport.Response.description', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='dlkit.proto.transport.Response.displayName', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genusTypeId', full_name='dlkit.proto.transport.Response.genusTypeId', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='dlkit.proto.transport.Response.id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recordTypeIds', full_name='dlkit.proto.transport.Response.recordTypeIds', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=901,
)


_DATAINPUTSTREAM = _descriptor.Descriptor(
  name='DataInputStream',
  full_name='dlkit.proto.transport.DataInputStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=903,
  serialized_end=920,
)


_DATAOUTPUTSTREAM = _descriptor.Descriptor(
  name='DataOutputStream',
  full_name='dlkit.proto.transport.DataOutputStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=922,
  serialized_end=940,
)

_ENDPOINT.fields_by_name['description'].message_type = dlkit_dot_primordium_dot_locale_dot_primitives__pb2._DISPLAYTEXT
_ENDPOINT.fields_by_name['displayName'].message_type = dlkit_dot_primordium_dot_locale_dot_primitives__pb2._DISPLAYTEXT
_ENDPOINT.fields_by_name['genusTypeId'].message_type = dlkit_dot_primordium_dot_type_dot_primitives__pb2._TYPE
_ENDPOINT.fields_by_name['id'].message_type = dlkit_dot_primordium_dot_id_dot_primitives__pb2._ID
_ENDPOINT.fields_by_name['recordTypeIds'].message_type = dlkit_dot_primordium_dot_type_dot_primitives__pb2._TYPE
_ENDPOINTLIST.fields_by_name['endpoints'].message_type = _ENDPOINT
_RESPONSE.fields_by_name['description'].message_type = dlkit_dot_primordium_dot_locale_dot_primitives__pb2._DISPLAYTEXT
_RESPONSE.fields_by_name['displayName'].message_type = dlkit_dot_primordium_dot_locale_dot_primitives__pb2._DISPLAYTEXT
_RESPONSE.fields_by_name['genusTypeId'].message_type = dlkit_dot_primordium_dot_type_dot_primitives__pb2._TYPE
_RESPONSE.fields_by_name['id'].message_type = dlkit_dot_primordium_dot_id_dot_primitives__pb2._ID
_RESPONSE.fields_by_name['recordTypeIds'].message_type = dlkit_dot_primordium_dot_type_dot_primitives__pb2._TYPE
DESCRIPTOR.message_types_by_name['Endpoint'] = _ENDPOINT
DESCRIPTOR.message_types_by_name['EndpointList'] = _ENDPOINTLIST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['DataInputStream'] = _DATAINPUTSTREAM
DESCRIPTOR.message_types_by_name['DataOutputStream'] = _DATAOUTPUTSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Endpoint = _reflection.GeneratedProtocolMessageType('Endpoint', (_message.Message,), dict(
  DESCRIPTOR = _ENDPOINT,
  __module__ = 'dlkit.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.transport.Endpoint)
  ))
_sym_db.RegisterMessage(Endpoint)

EndpointList = _reflection.GeneratedProtocolMessageType('EndpointList', (_message.Message,), dict(
  DESCRIPTOR = _ENDPOINTLIST,
  __module__ = 'dlkit.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.transport.EndpointList)
  ))
_sym_db.RegisterMessage(EndpointList)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'dlkit.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.transport.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'dlkit.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.transport.Response)
  ))
_sym_db.RegisterMessage(Response)

DataInputStream = _reflection.GeneratedProtocolMessageType('DataInputStream', (_message.Message,), dict(
  DESCRIPTOR = _DATAINPUTSTREAM,
  __module__ = 'dlkit.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.transport.DataInputStream)
  ))
_sym_db.RegisterMessage(DataInputStream)

DataOutputStream = _reflection.GeneratedProtocolMessageType('DataOutputStream', (_message.Message,), dict(
  DESCRIPTOR = _DATAOUTPUTSTREAM,
  __module__ = 'dlkit.proto.transport_pb2'
  # @@protoc_insertion_point(class_scope:dlkit.proto.transport.DataOutputStream)
  ))
_sym_db.RegisterMessage(DataOutputStream)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
